'use strict';
// noinspection JSUnusedLocalSymbols
module.exports = {PING_TYPE: 1, PONG_TYPE: 1, APPLICATION_COMMAND_TYPE: 2, MESSAGE_COMPONENT_TYPE: 3, APPLICATION_COMMAND_AUTOCOMPLETE_TYPE: 4,
    CHANNEL_MESSAGE_WITH_SOURCE_RESPONSE_TYPE: 4, UPDATE_MESSAGE_RESPONSE_TYPE: 7
}
